Feature/tree list
the-web-forest/Forest pull request #7
Opened 2022-08-04 02:00 UTC by hiagoindalecio

Adding the trees filter by name, description or biome.

2022-08-10 23:32 UTC, hiagoindalecio commented on Ipe/Util/ReasonBuilder.cs
> +#nullable enable
Esse comentário é uma flag exigida a partir do C# 8.0 para referências anuláveis. Segue referência:
https://docs.microsoft.com/pt-br/dotnet/csharp/nullable-references

2022-08-10 23:38 UTC, hiagoindalecio commented on Ipe/External/Repositories/TreeRepository.cs
> +        public async Task<GetTreesByFilterOutputUseCase> GetTreesByFilter(GetTreesByFilterInputUseCase filter)
Mesmo que forem comentários explicativos? Tenho o costume de colocar breves explicações caso o código seja muito complicado

2022-08-10 23:50 UTC, hiagoindalecio commented on Ipe/UseCases/TreeUseCase/GetTreesByFilter/GetTreesByFilterInputUseCase.cs
> +#nullable disable
Esse comentário é uma flag exigida a partir do C# 8.0 para referências anuláveis. Segue referência:
https://docs.microsoft.com/pt-br/dotnet/csharp/nullable-references

2022-08-10 23:51 UTC, hiagoindalecio commented on Ipe/Domain/Models/Tree.cs
> +#nullable enable
"// Props for filter" removido

2022-08-11 02:48 UTC, Barros42 requested changes

2022-08-11 02:48 UTC, Barros42 commented on Ipe/UseCases/Interfaces/Repositories/ITreeRepository.cs
> +        Task<GetTreesByFilterUseCaseOutput> GetTreesByFilter(GetTreesByFilterUseCaseInput filter);
Repositório não pode devolver o tipo GetTreesByFilterUseCaseOutput por pertencer ao UseCase, criar novo Tipo para conter Árvores e Total

2022-08-11 02:48 UTC, Barros42 commented on Ipe/UseCases/TreeUseCase/GetTreesByFilter/GetTreesByFilterUseCase.cs
> +namespace Ipe.UseCases.TreeUseCase.GetTreesByFilter
Não utilizar FluentResults, vamos discutir a implementação, seguir padrão do projeto.

2022-08-11 02:48 UTC, Barros42 commented on Ipe/Domain/Models/TreeByFilter.cs
> +        public TreeByFilter(string name, string description, string image, double value, string biome)
Devolver ID da árvore

2022-08-11 02:48 UTC, Barros42 commented on Ipe/Domain/Models/TreeByFilter.cs
> +﻿namespace Ipe.Domain.Models
Pasta Models exclusiva para models de Database, favor criar e mover o TreeByFilter.cs para outra pasta

2022-08-11 02:48 UTC, Barros42 commented on Ipe/External/Repositories/TreeRepository.cs
> +
**Remover comentários do código**

2022-08-12 01:12 UTC, hiagoindalecio commented on Ipe/Domain/Models/TreeByFilter.cs
> +﻿namespace Ipe.Domain.Models
Classe movida para a pasta de classes específicas do use case

2022-08-12 02:29 UTC, Barros42 approved these changes

2022-08-12 02:29 UTC, merged